import "./PrivacyP.css";
import InformationPost from "../organism/informationPost";
import HeaderTC from '../molecules/HeaderTC/headerTc';

export default function PrivacyP() {
    return (
        <main className='generalPrivacyP'>
            <div className = 'HeaderPrivacy'>
                <HeaderTC 
                    title = "Políticas de privacidad" 
                    button1 = "Configuración de privacidad"
                    button2 = "Descargar PDF"
                />
            </div>
            <div className = 'BodyPrivacy'>
                <InformationPost title = "Políticas de privacidad"
                title1 = "Introducción" text1 = "En PickEngine, entendemos la importancia de proteger tu información personal y estamos comprometidos con la seguridad de tus datos. Esta política de privacidad describe cómo recopilamos, usamos y compartimos la información que nos proporcionas. Nuestra aplicación está diseñada para ofrecerte una experiencia interactiva centrada en el automovilismo, que incluye recomendaciones personalizadas a través de inteligencia artificial (IA), la creación de modelos 3D de vehículos y una red social donde puedes interactuar con otros entusiastas del automovilismo. La recopilación de datos se realiza con el fin de mejorar la experiencia del usuario y hacer que el contenido sea más relevante."
                title2 = "Información Recopilada" text2 = "Recopilamos varios tipos de información para ofrecerte una experiencia personalizada y mejorar nuestras funcionalidades: Datos personales: Incluyen tu nombre, correo electrónico, número de teléfono y, en algunos casos, información de pago si decides realizar compras dentro de la aplicación. Datos de perfil: Información relacionada con tus preferencias en automovilismo, tus interacciones dentro de la app y cualquier dato que decidas compartir en tu perfil, como tu foto de perfil o biografía. Datos generados por IA: La IA utiliza tu historial de uso para ofrecerte recomendaciones personalizadas sobre vehículos, contenido y configuraciones de modelado 3D basadas en tus intereses. Datos de modelado 3D: Cuando creas o subes modelos 3D de vehículos, almacenamos las imágenes y configuraciones que elijas para personalizar tu experiencia visual. Interacciones en la red social: Incluye publicaciones, comentarios, me gusta y mensajes que compartas con otros usuarios dentro de nuestra comunidad de automovilismo."
                title3 = "Uso de la Información Recopilada" text3 = "La información recopilada se utiliza para: Personalizar la experiencia del usuario: Para que te ofrezcamos contenido y recomendaciones que coincidan con tus intereses en automovilismo. Mejorar la IA: Utilizamos los datos generados por ti para mejorar la precisión de las recomendaciones automatizadas, como vehículos sugeridos y configuraciones de modelado 3D. Crear y ajustar modelos 3D: Los datos de modelado que subes se utilizan para generar experiencias visuales ajustadas a tus preferencias. Facilitar la interacción en la red social: Tus publicaciones, comentarios y reacciones en la red social son visibles para otros usuarios, lo que fomenta la interacción dentro de la comunidad. Realizar análisis: Utilizamos datos agregados para mejorar las funciones y el rendimiento de la aplicación, y ofrecer contenido más relevante y atractivo."
                title4 = "Compartición de la Información" text4 = "Podemos compartir tu información con terceros en las siguientes circunstancias: Proveedores de servicios: Empresas que nos ayudan con almacenamiento de datos en la nube, análisis de datos, y procesamiento de pagos. Socios de automovilismo: Colaboramos con marcas de automovilismo y otros proveedores para ofrecerte contenido relevante, pero nunca compartimos tus datos personales sin tu consentimiento explícito. Redes sociales: La información que compartes públicamente en la red social de la aplicación será accesible para otros usuarios, de acuerdo con las configuraciones de privacidad que elijas. No vendemos ni compartimos tu información con terceros sin tu consentimiento previo, salvo en los casos descritos anteriormente."
                title5 = "Seguridad de los Datos" text5 = "Nos comprometemos a proteger tus datos personales mediante el uso de encriptación avanzada, protocolos de seguridad como HTTPS y políticas estrictas de control de acceso. Sólo empleados autorizados pueden acceder a los datos, y utilizamos medidas para proteger la integridad de los datos generados por la IA y el modelado 3D."
                title6 = "Retención y Eliminación de Datos" text6 = "Conservamos tus datos personales durante el tiempo que sea necesario para cumplir con los fines establecidos en esta política de privacidad. Puedes solicitar la eliminación de tu cuenta y todos tus datos en cualquier momento, y procesaremos tu solicitud tan pronto como sea posible. Si decides eliminar tu cuenta, eliminaremos tus datos de nuestra base de datos, aunque ciertos datos podrían ser conservados por razones legales o de seguridad."
                title7 = "Derechos del Usuario" text7 = "Tienes los siguientes derechos con respecto a tu información: Acceso a tus datos: Puedes solicitar en cualquier momento una copia de la información personal que tenemos sobre ti. Corrección de información: Si tus datos son inexactos o están incompletos, puedes corregirlos fácilmente a través de la aplicación. Eliminación de datos: Puedes solicitar que eliminemos tu información personal, incluyendo tu cuenta, en cualquier momento. Oposición al procesamiento de datos: Tienes derecho a oponerte al uso de tus datos para personalización a través de IA o cualquier otro propósito de marketing. Configuración de preferencias de privacidad: Puedes ajustar tus preferencias de privacidad dentro de la aplicación para controlar qué datos compartes y cómo se usan."
                title8 = "Cookies y Tecnologías de Seguimiento" text8 = "Utilizamos cookies y tecnologías de seguimiento para mejorar la funcionalidad de la aplicación, personalizar tu experiencia y analizar el uso de la misma. Las cookies nos permiten recordar tu configuración y preferencias, así como ofrecerte contenido relevante basado en tu actividad. Puedes gestionar tus preferencias de cookies a través de la configuración de la aplicación o de tu navegador."
                title9 = "Enlaces a Otros Sitios Web" text9 = "Nuestra aplicación puede contener enlaces a sitios web de terceros, como eventos de automovilismo o tiendas relacionadas. No somos responsables de las prácticas de privacidad de estos sitios, por lo que te recomendamos leer sus políticas de privacidad antes de proporcionarles tu información personal."
                title10 = "Actualizaciones de la Política de Privacidad" text10 = "Nos reservamos el derecho de actualizar esta política de privacidad de vez en cuando. Cuando realicemos cambios significativos, te notificaremos a través de la aplicación o por correo electrónico. La fecha de la última actualización estará siempre disponible en la parte inferior de esta página." />
            </div>
        </main>
    );
}
